# Generated by Django 2.2.10 on 2020-03-06 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prospect',
            fields=[
                ('prospect_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('prospect_full_name', models.CharField(max_length=50)),
                ('prospect_company', models.CharField(max_length=100)),
                ('prospect_designation', models.CharField(max_length=50)),
                ('prospect_skype_id', models.CharField(max_length=50)),
                ('prospect_street_address', models.CharField(max_length=40)),
                ('prospect_city', models.CharField(max_length=20)),
                ('prospect_state', models.CharField(max_length=20)),
                ('prospect_country', models.CharField(max_length=55)),
                ('prospect_phone', models.BigIntegerField(unique=True)),
                ('prospect_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=25)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='lead',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('lead_title', models.CharField(max_length=50)),
                ('lead_source', models.CharField(max_length=50)),
                ('lead_description', models.TextField()),
                ('lead_url', models.URLField()),
                ('lead_domain', models.CharField(max_length=50)),
                ('lead_technology', models.CharField(max_length=50)),
                ('lead_estimated_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lead_reffered_by', models.CharField(max_length=50)),
                ('lead_assignee', models.CharField(max_length=50)),
                ('lead_status', models.CharField(default='New', max_length=20)),
                ('lead_keyword_tags', models.CharField(max_length=100)),
                ('lead_prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect', to='API.prospect')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField()),
                ('comment_date', models.DateField(auto_now=True)),
                ('comment_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='API.lead')),
            ],
        ),
        migrations.CreateModel(
            name='attachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('attachment', models.FileField(upload_to='uploads/')),
                ('attachment_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='API.lead')),
            ],
        ),
    ]
