# Generated by Django 2.2.10 on 2020-02-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_keyword_tags',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
