# Generated by Django 2.2.10 on 2020-02-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200227_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='prospect_skype_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
